version: "2"

services:
  rng:
    build: https://raw.githubusercontent.com/nheinemans/orchestration-workshop/master/dockercoins/rng/Dockerfile
    ports:
    - "8001:80"

  hasher:
    build: https://raw.githubusercontent.com/nheinemans/orchestration-workshop/master/dockercoins/hasher/Dockerfile
    ports:
    - "8002:80"

  webui:
    build: https://raw.githubusercontent.com/nheinemans/orchestration-workshop/master/dockercoins/webui/Dockerfile
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis

  worker:
    build: https://raw.githubusercontent.com/nheinemans/orchestration-workshop/master/dockercoins/worker/Dockerfile

